defaults:
  - experiment: efficientnet_prcnn_mfcc

hydra:
  output_subdir: null
  run:
    dir: .

experiment:
  data:
    # dataset_path: /content/drive/MyDrive/music_genre_classification/data
    # label_path: /content/drive/MyDrive/music_genre_classification/genre_labels.json
    dataset_path: ./data
    label_path: ./data/genre_labels.json
  training:
    checkpoint_path: ./checkpoint
    load: True
    initial_epoch: 1
  wandb:
    log: True
    project_name: music-genre-classification
    entity: kaung-htet
    group: tests
    resume: allow
    name: test_exp_03
    id: test_exp_03