defaults:
  - experiment: inceptionv3_prcnn_melspectrogram

hydra:
  output_subdir: null
  run:
    dir: .

experiment:
  data:
    dataset_path: ./data
    label_path: ./data/genre_labels.json
  training:
    checkpoint_path: ./checkpoint
    load: False
    initial_epoch: 0
  wandb:
    log: True
    project_name: music-genre-classification
    entity: kaung-htet
    group: null
    resume: allow
    name: null
    id: null