defaults:
  - experiment: resnet_linear_melspectrogram

hydra:
  output_subdir: null
  run:
    dir: .

experiment:
  data:
    dataset_path: ./data
    label_path: ./data/genre_labels.json
  training:
    checkpoint_path: ./checkpoint